In [2]:
import numpy as np
import pandas as pd

In [3]:
df= pd.read_csv("netflix_titles.csv")
df.head(10)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
5,s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",The arrival of a charismatic young priest brin...
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,"September 24, 2021",2021,PG,91 min,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
8,s9,TV Show,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,"September 24, 2021",2021,TV-14,9 Seasons,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...

In [4]:
ratings= df["rating"].to_numpy()
types= df["type"].to_numpy()
year_of_release= df["release_year"].to_numpy()
duration= df["duration"].to_numpy()
listed= df["listed_in"].to_numpy()
show_title= df["title"].to_numpy()
show_directors= df["director"].to_numpy()
casting= df["cast"].to_numpy()
show_region= df["country"].to_numpy()
show_dates= df["date_added"].to_numpy()

In [5]:
print("Ratings:", ratings)
print("Types:", types)
print("Year:", year_of_release)
print("Duration:", duration)
print("Listed in:", listed)

Ratings: ['PG-13' 'TV-MA' 'TV-MA' ... 'R' 'PG' 'TV-14']
Types: ['Movie' 'TV Show' 'TV Show' ... 'Movie' 'Movie' 'Movie']
Year: [2020 2021 2021 ... 2009 2006 2015]
Duration: ['90 min' '2 Seasons' '1 Season' ... '88 min' '88 min' '111 min']
Listed in: ['Documentaries' 'International TV Shows, TV Dramas, TV Mysteries'
 'Crime TV Shows, International TV Shows, TV Action & Adventure' ...
 'Comedies, Horror Movies' 'Children & Family Movies, Comedies'
 'Dramas, International Movies, Music & Musicals']

In [6]:
np.array(df["release_year"])
df.values
df.to_numpy()

array([['s1', 'Movie', 'Dick Johnson Is Dead', ..., '90 min',
        'Documentaries',
        'As her father nears the end of his life, filmmaker Kirsten Johnson stages his death in inventive and comical ways to help them both face the inevitable.'],
       ['s2', 'TV Show', 'Blood & Water', ..., '2 Seasons',
        'International TV Shows, TV Dramas, TV Mysteries',
        'After crossing paths at a party, a Cape Town teen sets out to prove whether a private-school swimming star is her sister who was abducted at birth.'],
       ['s3', 'TV Show', 'Ganglands', ..., '1 Season',
        'Crime TV Shows, International TV Shows, TV Action & Adventure',
        'To protect his family from a powerful drug lord, skilled thief Mehdi and his expert team of robbers are pulled into a violent and deadly turf war.'],
       ...,
       ['s8805', 'Movie', 'Zombieland', ..., '88 min',
        'Comedies, Horror Movies',
        'Looking to survive in a world taken over by zombies, a dorky college student teams with an urban roughneck and a pair of grifter sisters.'],
       ['s8806', 'Movie', 'Zoom', ..., '88 min',
        'Children & Family Movies, Comedies',
        'Dragged from civilian life, a former superhero must train a new crop of youthful saviors when the military preps for an attack by a familiar villain.'],
       ['s8807', 'Movie', 'Zubaan', ..., '111 min',
        'Dramas, International Movies, Music & Musicals',
        "A scrappy but poor boy worms his way into a tycoon's dysfunctional family, while facing his fear of music and the truth about his past."]],
      shape=(8807, 12), dtype=object)

In [7]:
np.unique(year_of_release)
np.arange(year_of_release.min(), year_of_release.max())

array([1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932, 1933, 1934, 1935,
       1936, 1937, 1938, 1939, 1940, 1941, 1942, 1943, 1944, 1945, 1946,
       1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957,
       1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968,
       1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979,
       1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990,
       1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001,
       2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012,
       2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020])

Handling missing values

1) Detecting missing values

In [8]:
dtct_missing_ratings= pd.isna(ratings)
dtct_missing_types= pd.isna(types)
dtct_missing_years= np.isnan(year_of_release)
dtct_missing_durations= pd.isna(duration)
dtct_missing_list= pd.isna(listed)
dtct_missing_title= pd.isna(show_title)
dtct_missing_directors= pd.isna(show_directors)
dtct_missing_cast= pd.isna(casting)
dtct_missing_country= pd.isna(show_region)
dtct_missing_dates= pd.isna(show_dates)

In [46]:
dtct_missing_directors

array([False,  True, False, ..., False, False, False], shape=(8807,))

2. Counting missing values

In [10]:
np.sum(dtct_missing_directors)

np.int64(2634)

3. Removing Missing Values

In [49]:
# for single column
df_clean = df.dropna(subset=["director"])
df_clean

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
5,s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",The arrival of a charismatic young priest brin...
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,"September 24, 2021",2021,PG,91 min,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
...,...,...,...,...,...,...,...,...,...,...,...,...
8801,s8802,Movie,Zinzana,Majid Al Ansari,"Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jabri, ...","United Arab Emirates, Jordan","March 9, 2016",2015,TV-MA,96 min,"Dramas, International Movies, Thrillers",Recovering alcoholic Talal wakes up inside a s...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [51]:
# for every column
df_clean_all= df.dropna()
df_clean_all

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
8,s9,TV Show,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,"September 24, 2021",2021,TV-14,9 Seasons,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...
12,s13,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis Niewöhner, Milan Peschel, ...","Germany, Czech Republic","September 23, 2021",2021,TV-MA,127 min,"Dramas, International Movies",After most of her family is murdered in a terr...
24,s25,Movie,Jeans,S. Shankar,"Prashanth, Aishwarya Rai Bachchan, Sri Lakshmi...",India,"September 21, 2021",1998,TV-14,166 min,"Comedies, International Movies, Romantic Movies",When the father of the man she loves insists t...
...,...,...,...,...,...,...,...,...,...,...,...,...
8801,s8802,Movie,Zinzana,Majid Al Ansari,"Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jabri, ...","United Arab Emirates, Jordan","March 9, 2016",2015,TV-MA,96 min,"Dramas, International Movies, Thrillers",Recovering alcoholic Talal wakes up inside a s...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

Filtering and Boolean Masking

1. Movies released after 2016

In [12]:
movies_post2016= year_of_release[year_of_release > 2016]

In [13]:
np.count_nonzero(movies_post2016)

np.int64(4754)

2. Boolean masks

In [14]:
masks= year_of_release>= 2016
df[masks]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8787,s8788,Movie,You Can’t Fight Christmas,Kenny Young,"Brely Evans, Andra Fuller, Persia White, Porsc...",United States,"December 19, 2017",2017,TV-PG,85 min,"Comedies, Romantic Movies",After stepping in to revitalize his family's h...
8794,s8795,Movie,اشتباك,Mohamed Diab,"Nelly Karim, Hany Adel, Tarek Abdel Aziz, Ahme...","Egypt, France","October 11, 2018",2016,TV-14,98 min,"Dramas, Independent Movies, International Movies",Amid the tumult following Egyptian President M...
8796,s8797,TV Show,Yunus Emre,NaN,"Gökhan Atalay, Payidar Tüfekçioglu, Baran Akbu...",Turkey,"January 17, 2017",2016,TV-PG,2 Seasons,"International TV Shows, TV Dramas","During the Mongol invasions, Yunus Emre leaves..."
8797,s8798,TV Show,Zak Storm,NaN,"Michael Johnston, Jessica Gee-George, Christin...","United States, France, South Korea, Indonesia","September 13, 2018",2016,TV-Y7,3 Seasons,Kids' TV,Teen surfer Zak Storm is mysteriously transpor...
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."

3. Netflix Movies Only

In [15]:
movies_only= types== "Movie"
df[movies_only]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,"September 24, 2021",2021,PG,91 min,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...
12,s13,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis Niewöhner, Milan Peschel, ...","Germany, Czech Republic","September 23, 2021",2021,TV-MA,127 min,"Dramas, International Movies",After most of her family is murdered in a terr...
...,...,...,...,...,...,...,...,...,...,...,...,...
8801,s8802,Movie,Zinzana,Majid Al Ansari,"Ali Suliman, Saleh Bakri, Yasa, Ali Al-Jabri, ...","United Arab Emirates, Jordan","March 9, 2016",2015,TV-MA,96 min,"Dramas, International Movies, Thrillers",Recovering alcoholic Talal wakes up inside a s...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

Statistical operations

1. Release year statistics

In [16]:
mean_year= np.mean(year_of_release)
median_year=np.median(year_of_release)
min_year=np.min(year_of_release)
max_year=np.max(year_of_release)
std_year=np.std(year_of_release)

In [17]:
min_year

np.int64(1925)

In [18]:
var_year= np.var(year_of_release)
range_year= np.max(year_of_release)-np.min(year_of_release)

In [19]:
range_year

np.int64(96)

Frequency and Counting operations

1. Counting Movies vs TV shows

In [20]:
np.unique(types, return_counts=True)

(array(['Movie', 'TV Show'], dtype=object), array([6131, 2676]))

2. Counting contents per year

In [21]:
unique_years ,counts= np.unique(year_of_release, return_counts=True)
unique_years

array([1925, 1942, 1943, 1944, 1945, 1946, 1947, 1954, 1955, 1956, 1958,
       1959, 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969,
       1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980,
       1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991,
       1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
       2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013,
       2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021])

In [22]:
counts

array([   1,    2,    3,    3,    4,    2,    1,    2,    3,    2,    3,
          1,    4,    1,    3,    2,    2,    2,    1,    5,    3,    2,
          2,    5,    5,   10,    7,    7,    9,    7,    7,   11,   11,
         13,   17,   11,   12,   10,   13,    8,   18,   16,   22,   17,
         23,   28,   22,   25,   24,   38,   36,   39,   37,   45,   51,
         61,   64,   80,   96,   88,  136,  152,  194,  185,  237,  288,
        352,  560,  902, 1032, 1147, 1030,  953,  592])

String Operations

1. Converting text to numpy string array

In [23]:
countries= df["country"].dropna().to_numpy(dtype=str)
countries

array(['United States', 'South Africa', 'India', ..., 'United States',
       'United States', 'India'], shape=(7976,), dtype='<U123')

In [24]:
indian_movies= np.count_nonzero((df["type"]=="Movie") & df["country"].str.contains("India", na=False))
indian_movies

np.int64(962)

2. String Contains

In [25]:
np.char.find(countries, "India")>=0

array([False, False,  True, ..., False, False,  True], shape=(7976,))

3. Upper/ Lower case

In [26]:
np.char.upper(countries)

array(['UNITED STATES', 'SOUTH AFRICA', 'INDIA', ..., 'UNITED STATES',
       'UNITED STATES', 'INDIA'], shape=(7976,), dtype='<U123')

Sorting Operations

1. Sorting by year of release

In [27]:
np.sort(year_of_release )

array([1925, 1942, 1942, ..., 2021, 2021, 2021], shape=(8807,))

2. Sort with indices

In [28]:
indices= np.argsort(year_of_release)
df.iloc[indices]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
4250,s4251,TV Show,Pioneers: First Women Filmmakers*,NaN,NaN,NaN,"December 30, 2018",1925,TV-14,1 Season,TV Shows,This collection restores films from women who ...
7790,s7791,Movie,Prelude to War,Frank Capra,NaN,United States,"March 31, 2017",1942,TV-14,52 min,"Classic Movies, Documentaries",Frank Capra's documentary chronicles the rise ...
8205,s8206,Movie,The Battle of Midway,John Ford,"Henry Fonda, Jane Darwell",United States,"March 31, 2017",1942,TV-14,18 min,"Classic Movies, Documentaries",Director John Ford captures combat footage of ...
8739,s8740,Movie,Why We Fight: The Battle of Russia,"Frank Capra, Anatole Litvak",NaN,United States,"March 31, 2017",1943,TV-PG,82 min,Documentaries,This installment of Frank Capra's acclaimed do...
8763,s8764,Movie,WWII: Report from the Aleutians,John Huston,NaN,United States,"March 31, 2017",1943,TV-PG,45 min,Documentaries,Filmmaker John Huston narrates this Oscar-nomi...
...,...,...,...,...,...,...,...,...,...,...,...,...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
18,s19,Movie,Intrusion,Adam Salky,"Freida Pinto, Logan Marshall-Green, Robert Joh...",NaN,"September 22, 2021",2021,TV-14,94 min,Thrillers,After a deadly home invasion at a couple’s new...
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
68,s69,Movie,Schumacher,"Hanns-Bruno Kammertöns, Vanessa Nöcker, Michae...",Michael Schumacher,NaN,"September 15, 2021",2021,TV-14,113 min,"Documentaries, International Movies, Sports Mo...",Through exclusive interviews and archival foot...

In [29]:
sorted_years= year_of_release[indices]
sorted_years

array([1925, 1942, 1942, ..., 2021, 2021, 2021], shape=(8807,))

Mathematical and Logical operations

1. Compare years

In [30]:
year_of_release>2016

array([ True,  True,  True, ..., False, False, False], shape=(8807,))

In [31]:
year_of_release== 2020

array([ True, False, False, ..., False, False, False], shape=(8807,))

2. Logical Operations

In [32]:
np.logical_and(year_of_release>2010, year_of_release<2020)

array([False, False, False, ..., False, False,  True], shape=(8807,))

Vectorized Operations(no loops)

1. Add year_of_release offset

In [33]:
year_of_release+1

array([2021, 2022, 2022, ..., 2010, 2007, 2016], shape=(8807,))

2. Age of content

In [34]:
content_age= 2026- year_of_release
content_age

array([ 6,  5,  5, ..., 17, 20, 11], shape=(8807,))

Indexing and slicing

1. First 15 entries

In [35]:
year_of_release[:15]

array([2020, 2021, 2021, 2021, 2021, 2021, 2021, 1993, 2021, 2021, 2021,
       2021, 2021, 2021, 2021])

2. Every 5th entry

In [36]:
year_of_release[::5]

array([2020, 2021, 2021, ..., 2015, 2012, 2006], shape=(1762,))

Aggregation by Categories (Hybrid NumPy Logic)

In [37]:
movies_per_year= year_of_release[movies_only]
np.unique(movies_per_year, return_counts=True)

(array([1942, 1943, 1944, 1945, 1946, 1947, 1954, 1955, 1956, 1958, 1959,
        1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970,
        1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981,
        1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992,
        1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003,
        2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014,
        2015, 2016, 2017, 2018, 2019, 2020, 2021]),
 array([  2,   3,   3,   3,   1,   1,   2,   3,   2,   3,   1,   4,   1,
          3,   1,   2,   2,   1,   4,   3,   2,   2,   5,   4,  10,   6,
          7,   9,   6,   7,  10,  11,  12,  17,  11,  12,   9,  11,   8,
         16,  15,  19,  16,  20,  24,  20,  23,  21,  34,  32,  32,  33,
         40,  44,  51,  55,  67,  82,  74, 113, 118, 154, 145, 173, 225,
        264, 398, 658, 767, 767, 633, 517, 277]))

Correlation & Relationships

In [38]:
np.corrcoef(year_of_release, content_age)

array([[ 1., -1.],
       [-1.,  1.]])

Broadcasting

In [39]:
year_of_release- np.mean(year_of_release)

array([ 5.81980243,  6.81980243,  6.81980243, ..., -5.18019757,
       -8.18019757,  0.81980243], shape=(8807,))

Random sampling

In [40]:
# unique indeces
sample_index= np.random.choice(year_of_release, size=10, replace=False)
sample_index

array([2016, 2018, 2021, 2014, 2020, 2011, 2015, 2008, 2016, 2018])

In [41]:
# unique values
sample_value= np.random.choice(unique_years, size=10, replace=False)
sample_value

array([2016, 1956, 2003, 1964, 1999, 2015, 1981, 1970, 2000, 2021])

Reshaping and structuring

In [42]:
year_of_release.reshape(-1, 1)

array([[2020],
       [2021],
       [2021],
       ...,
       [2009],
       [2006],
       [2015]], shape=(8807, 1))

In [43]:
np.column_stack((year_of_release, content_age))

array([[2020,    6],
       [2021,    5],
       [2021,    5],
       ...,
       [2009,   17],
       [2006,   20],
       [2015,   11]], shape=(8807, 2))

Performance Optimization

In [44]:
ages= []
for y in year_of_release:
    ages.append(2026-y)

In [45]:
ages

[np.int64(6),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(33),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(6),
 np.int64(6),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(8),
 np.int64(30),
 np.int64(5),
 np.int64(28),
 np.int64(5),
 np.int64(29),
 np.int64(16),
 np.int64(13),
 np.int64(13),
 np.int64(5),
 np.int64(5),
 np.int64(6),
 np.int64(5),
 np.int64(6),
 np.int64(5),
 np.int64(5),
 np.int64(8),
 np.int64(9),
 np.int64(5),
 np.int64(5),
 np.int64(51),
 np.int64(48),
 np.int64(43),
 np.int64(39),
 np.int64(5),
 np.int64(14),
 np.int64(6),
 np.int64(25),
 np.int64(5),
 np.int64(12),
 np.int64(24),
 np.int64(23),
 np.int64(22),
 np.int64(25),
 np.int64(5),
 np.int64(15),
 np.int64(18),
 np.int64(17),
 np.int64(19),
 np.int64(16),
 np.int64(21),
 np.int64(20),
 np.int64(22),
 np.int64(5),
 np.int64(5),
 np.int64(12),
 np.int64(32),
 np.int64(5),
 np.int64(11),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(8),
 np.int64(5),
 np.int64(5),
 np.int64(13),
 np.int64(5),
 np.int64(6),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(6),
 np.int64(5),
 np.int64(5),
 np.int64(7),
 np.int64(5),
 np.int64(9),
 np.int64(7),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(8),
 np.int64(5),
 np.int64(8),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(7),
 np.int64(5),
 np.int64(5),
 np.int64(6),
 np.int64(10),
 np.int64(9),
 np.int64(5),
 np.int64(8),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(32),
 np.int64(17),
 np.int64(11),
 np.int64(5),
 np.int64(9),
 np.int64(6),
 np.int64(5),
 np.int64(7),
 np.int64(23),
 np.int64(14),
 np.int64(13),
 np.int64(5),
 np.int64(6),
 np.int64(22),
 np.int64(9),
 np.int64(21),
 np.int64(5),
 np.int64(44),
 np.int64(5),
 np.int64(11),
 np.int64(32),
 np.int64(33),
 np.int64(23),
 np.int64(25),
 np.int64(16),
 np.int64(37),
 np.int64(12),
 np.int64(11),
 np.int64(19),
 np.int64(15),
 np.int64(36),
 np.int64(35),
 np.int64(32),
 np.int64(5),
 np.int64(6),
 np.int64(28),
 np.int64(27),
 np.int64(21),
 np.int64(10),
 np.int64(10),
 np.int64(11),
 np.int64(40),
 np.int64(16),
 np.int64(8),
 np.int64(23),
 np.int64(16),
 np.int64(34),
 np.int64(30),
 np.int64(9),
 np.int64(23),
 np.int64(27),
 np.int64(7),
 np.int64(42),
 np.int64(18),
 np.int64(25),
 np.int64(20),
 np.int64(29),
 np.int64(9),
 np.int64(23),
 np.int64(11),
 np.int64(23),
 np.int64(46),
 np.int64(40),
 np.int64(65),
 np.int64(12),
 np.int64(30),
 np.int64(26),
 np.int64(5),
 np.int64(18),
 np.int64(33),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(18),
 np.int64(6),
 np.int64(5),
 np.int64(9),
 np.int64(18),
 np.int64(5),
 np.int64(24),
 np.int64(18),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(20),
 np.int64(22),
 np.int64(23),
 np.int64(21),
 np.int64(10),
 np.int64(14),
 np.int64(25),
 np.int64(16),
 np.int64(18),
 np.int64(16),
 np.int64(13),
 np.int64(15),
 np.int64(12),
 np.int64(10),
 np.int64(5),
 np.int64(5),
 np.int64(19),
 np.int64(15),
 np.int64(15),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(6),
 np.int64(12),
 np.int64(6),
 np.int64(5),
 np.int64(5),
 np.int64(7),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(8),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(6),
 np.int64(15),
 np.int64(5),
 np.int64(31),
 np.int64(5),
 np.int64(5),
 np.int64(6),
 np.int64(11),
 np.int64(6),
 np.int64(8),
 np.int64(6),
 np.int64(5),
 np.int64(5),
 np.int64(10),
 np.int64(12),
 np.int64(8),
 np.int64(6),
 np.int64(33),
 np.int64(6),
 np.int64(11),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(10),
 np.int64(6),
 np.int64(5),
 np.int64(5),
 np.int64(13),
 np.int64(5),
 np.int64(5),
 np.int64(8),
 np.int64(7),
 np.int64(5),
 np.int64(5),
 np.int64(14),
 np.int64(5),
 np.int64(6),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(6),
 np.int64(5),
 np.int64(5),
 np.int64(13),
 np.int64(13),
 np.int64(41),
 np.int64(5),
 np.int64(33),
 np.int64(10),
 np.int64(5),
 np.int64(14),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(17),
 np.int64(31),
 np.int64(16),
 np.int64(15),
 np.int64(5),
 np.int64(5),
 np.int64(21),
 np.int64(5),
 np.int64(13),
 np.int64(18),
 np.int64(14),
 np.int64(6),
 np.int64(34),
 np.int64(33),
 np.int64(19),
 np.int64(10),
 np.int64(24),
 np.int64(17),
 np.int64(6),
 np.int64(27),
 np.int64(40),
 np.int64(7),
 np.int64(20),
 np.int64(16),
 np.int64(19),
 np.int64(12),
 np.int64(5),
 np.int64(16),
 np.int64(27),
 np.int64(31),
 np.int64(35),
 np.int64(32),
 np.int64(11),
 np.int64(18),
 np.int64(17),
 np.int64(7),
 np.int64(23),
 np.int64(26),
 np.int64(22),
 np.int64(10),
 np.int64(13),
 np.int64(35),
 np.int64(15),
 np.int64(16),
 np.int64(22),
 np.int64(31),
 np.int64(26),
 np.int64(16),
 np.int64(5),
 np.int64(8),
 np.int64(5),
 np.int64(5),
 np.int64(12),
 np.int64(5),
 np.int64(6),
 np.int64(17),
 np.int64(5),
 np.int64(5),
 np.int64(17),
 np.int64(5),
 np.int64(5),
 np.int64(13),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(7),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(14),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(7),
 np.int64(7),
 np.int64(6),
 np.int64(14),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(11),
 np.int64(13),
 np.int64(17),
 np.int64(15),
 np.int64(16),
 np.int64(13),
 np.int64(13),
 np.int64(13),
 np.int64(13),
 np.int64(14),
 np.int64(17),
 np.int64(13),
 np.int64(11),
 np.int64(7),
 np.int64(16),
 np.int64(14),
 np.int64(12),
 np.int64(15),
 np.int64(15),
 np.int64(14),
 np.int64(7),
 np.int64(5),
 np.int64(7),
 np.int64(5),
 np.int64(6),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(6),
 np.int64(6),
 np.int64(7),
 np.int64(5),
 np.int64(5),
 np.int64(6),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(27),
 np.int64(5),
 np.int64(9),
 np.int64(9),
 np.int64(15),
 np.int64(14),
 np.int64(16),
 np.int64(17),
 np.int64(18),
 np.int64(5),
 np.int64(5),
 np.int64(43),
 np.int64(5),
 np.int64(7),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(19),
 np.int64(7),
 np.int64(7),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(7),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(6),
 np.int64(11),
 np.int64(7),
 np.int64(10),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(6),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(10),
 np.int64(5),
 np.int64(5),
 np.int64(9),
 np.int64(5),
 np.int64(9),
 np.int64(8),
 np.int64(5),
 np.int64(11),
 np.int64(7),
 np.int64(12),
 np.int64(5),
 np.int64(6),
 np.int64(5),
 np.int64(5),
 np.int64(6),
 np.int64(16),
 np.int64(5),
 np.int64(5),
 np.int64(6),
 np.int64(5),
 np.int64(7),
 np.int64(7),
 np.int64(7),
 np.int64(10),
 np.int64(9),
 np.int64(19),
 np.int64(8),
 np.int64(7),
 np.int64(7),
 np.int64(5),
 np.int64(9),
 np.int64(6),
 np.int64(6),
 np.int64(5),
 np.int64(5),
 np.int64(11),
 np.int64(7),
 np.int64(7),
 np.int64(8),
 np.int64(7),
 np.int64(10),
 np.int64(14),
 np.int64(50),
 np.int64(11),
 np.int64(8),
 np.int64(7),
 np.int64(5),
 np.int64(7),
 np.int64(11),
 np.int64(8),
 np.int64(8),
 np.int64(5),
 np.int64(6),
 np.int64(6),
 np.int64(8),
 np.int64(67),
 np.int64(6),
 np.int64(5),
 np.int64(6),
 np.int64(5),
 np.int64(5),
 np.int64(6),
 np.int64(6),
 np.int64(5),
 np.int64(5),
 np.int64(6),
 np.int64(7),
 np.int64(6),
 np.int64(13),
 np.int64(5),
 np.int64(8),
 np.int64(14),
 np.int64(29),
 np.int64(5),
 np.int64(24),
 np.int64(29),
 np.int64(27),
 np.int64(29),
 np.int64(6),
 np.int64(26),
 np.int64(31),
 np.int64(33),
 np.int64(7),
 np.int64(5),
 np.int64(5),
 np.int64(7),
 np.int64(18),
 np.int64(15),
 np.int64(16),
 np.int64(7),
 np.int64(5),
 np.int64(21),
 np.int64(38),
 np.int64(5),
 np.int64(31),
 np.int64(10),
 np.int64(15),
 np.int64(25),
 np.int64(8),
 np.int64(34),
 np.int64(6),
 np.int64(8),
 np.int64(7),
 np.int64(10),
 np.int64(18),
 np.int64(16),
 np.int64(26),
 np.int64(17),
 np.int64(27),
 np.int64(7),
 np.int64(20),
 np.int64(16),
 np.int64(7),
 np.int64(29),
 np.int64(42),
 np.int64(40),
 np.int64(37),
 np.int64(23),
 np.int64(46),
 np.int64(20),
 np.int64(18),
 np.int64(24),
 np.int64(16),
 np.int64(23),
 np.int64(14),
 np.int64(17),
 np.int64(6),
 np.int64(28),
 np.int64(28),
 np.int64(7),
 np.int64(5),
 np.int64(5),
 np.int64(6),
 np.int64(7),
 np.int64(6),
 np.int64(7),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(6),
 np.int64(5),
 np.int64(6),
 np.int64(14),
 np.int64(5),
 np.int64(7),
 np.int64(8),
 np.int64(7),
 np.int64(16),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(7),
 np.int64(10),
 np.int64(23),
 np.int64(22),
 np.int64(5),
 np.int64(12),
 np.int64(10),
 np.int64(11),
 np.int64(25),
 np.int64(5),
 np.int64(8),
 np.int64(5),
 np.int64(8),
 np.int64(8),
 np.int64(7),
 np.int64(6),
 np.int64(6),
 np.int64(6),
 np.int64(11),
 np.int64(8),
 np.int64(6),
 np.int64(45),
 np.int64(44),
 np.int64(38),
 np.int64(7),
 np.int64(7),
 np.int64(8),
 np.int64(7),
 np.int64(6),
 np.int64(8),
 np.int64(8),
 np.int64(6),
 np.int64(8),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(6),
 np.int64(45),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(7),
 np.int64(11),
 np.int64(5),
 np.int64(5),
 np.int64(6),
 np.int64(5),
 np.int64(5),
 np.int64(7),
 np.int64(14),
 np.int64(5),
 np.int64(8),
 np.int64(7),
 np.int64(5),
 np.int64(5),
 np.int64(10),
 np.int64(6),
 np.int64(5),
 np.int64(5),
 np.int64(6),
 np.int64(6),
 np.int64(5),
 np.int64(5),
 np.int64(54),
 np.int64(5),
 np.int64(13),
 np.int64(5),
 np.int64(5),
 np.int64(6),
 np.int64(21),
 np.int64(12),
 np.int64(5),
 np.int64(5),
 np.int64(12),
 np.int64(6),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(10),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(12),
 np.int64(14),
 np.int64(5),
 np.int64(12),
 np.int64(5),
 np.int64(7),
 np.int64(5),
 np.int64(13),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(8),
 np.int64(12),
 np.int64(19),
 np.int64(8),
 np.int64(5),
 np.int64(6),
 np.int64(5),
 np.int64(5),
 np.int64(11),
 np.int64(11),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(6),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(7),
 np.int64(6),
 np.int64(14),
 np.int64(25),
 np.int64(17),
 np.int64(13),
 np.int64(26),
 np.int64(7),
 np.int64(5),
 np.int64(29),
 np.int64(5),
 np.int64(15),
 np.int64(5),
 np.int64(13),
 np.int64(23),
 np.int64(25),
 np.int64(11),
 np.int64(11),
 np.int64(18),
 np.int64(16),
 np.int64(29),
 np.int64(7),
 np.int64(14),
 np.int64(15),
 np.int64(25),
 np.int64(29),
 np.int64(22),
 np.int64(14),
 np.int64(15),
 np.int64(17),
 np.int64(20),
 np.int64(20),
 np.int64(5),
 np.int64(9),
 np.int64(9),
 np.int64(12),
 np.int64(22),
 np.int64(42),
 np.int64(5),
 np.int64(25),
 np.int64(33),
 np.int64(45),
 np.int64(11),
 np.int64(21),
 np.int64(11),
 np.int64(30),
 np.int64(50),
 np.int64(5),
 np.int64(8),
 np.int64(7),
 np.int64(7),
 np.int64(8),
 np.int64(6),
 np.int64(5),
 np.int64(5),
 np.int64(10),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(8),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(10),
 np.int64(5),
 np.int64(12),
 np.int64(11),
 np.int64(5),
 np.int64(5),
 np.int64(6),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(6),
 np.int64(5),
 np.int64(17),
 np.int64(15),
 np.int64(6),
 np.int64(5),
 np.int64(5),
 np.int64(15),
 np.int64(20),
 np.int64(12),
 np.int64(9),
 np.int64(28),
 np.int64(29),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(10),
 np.int64(5),
 np.int64(5),
 np.int64(6),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(8),
 np.int64(6),
 np.int64(6),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(22),
 np.int64(8),
 np.int64(6),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(6),
 np.int64(6),
 np.int64(5),
 np.int64(7),
 np.int64(5),
 np.int64(5),
 np.int64(9),
 np.int64(5),
 np.int64(27),
 np.int64(6),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(9),
 np.int64(5),
 np.int64(6),
 np.int64(9),
 np.int64(6),
 np.int64(13),
 np.int64(7),
 np.int64(5),
 np.int64(5),
 np.int64(6),
 np.int64(8),
 np.int64(8),
 np.int64(5),
 np.int64(6),
 np.int64(16),
 np.int64(20),
 np.int64(16),
 np.int64(37),
 np.int64(9),
 np.int64(16),
 np.int64(21),
 np.int64(16),
 np.int64(17),
 np.int64(8),
 np.int64(14),
 np.int64(6),
 np.int64(9),
 np.int64(7),
 np.int64(13),
 np.int64(12),
 np.int64(13),
 np.int64(23),
 np.int64(18),
 np.int64(8),
 np.int64(6),
 np.int64(32),
 np.int64(17),
 np.int64(8),
 np.int64(15),
 np.int64(17),
 np.int64(24),
 np.int64(26),
 np.int64(10),
 np.int64(8),
 np.int64(34),
 np.int64(18),
 np.int64(5),
 np.int64(7),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(8),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(12),
 np.int64(15),
 np.int64(8),
 np.int64(5),
 np.int64(6),
 np.int64(7),
 np.int64(5),
 np.int64(9),
 np.int64(10),
 np.int64(12),
 np.int64(13),
 np.int64(11),
 np.int64(22),
 np.int64(11),
 np.int64(5),
 np.int64(11),
 np.int64(11),
 np.int64(10),
 np.int64(7),
 np.int64(5),
 np.int64(9),
 np.int64(11),
 np.int64(6),
 np.int64(6),
 np.int64(5),
 np.int64(6),
 np.int64(25),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 np.int64(5),
 ...]